CREATE TABLE IF NOT EXISTS "users" (
  "id" SERIAL PRIMARY KEY,
  "username" VARCHAR(255) UNIQUE NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "avatarUrl" VARCHAR(255),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "channels" (
  "id" SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "name" VARCHAR(255) UNIQUE NOT NULL,
  "description" TEXT,
  "avatarUrl" VARCHAR(255),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "videos" (
  "id" SERIAL PRIMARY KEY,
  "channelId" INTEGER NOT NULL REFERENCES "channels"("id") ON DELETE CASCADE,
  "category" VARCHAR(255),
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "videoUrl" VARCHAR(255) NOT NULL,
  "previewUrl" VARCHAR(255),
  "views" INTEGER DEFAULT 0,
  "duration" INTEGER,
  "visibility" VARCHAR(50) DEFAULT 'public',
  "allowComments" BOOLEAN DEFAULT TRUE,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "comments" (
  "id" SERIAL PRIMARY KEY,
  "channelId" INTEGER NOT NULL REFERENCES "channels"("id") ON DELETE CASCADE,
  "videoId" INTEGER NOT NULL REFERENCES "videos"("id") ON DELETE CASCADE,
  "parentCommentId" INTEGER REFERENCES "comments"("id") ON DELETE CASCADE,
  "text" TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "videoReactions" (
  "channelId" INTEGER NOT NULL REFERENCES "channels"("id") ON DELETE CASCADE,
  "videoId" INTEGER NOT NULL REFERENCES "videos"("id") ON DELETE CASCADE,
  "reactionType" VARCHAR(10) NOT NULL CHECK ("reactionType" IN ('like', 'dislike')),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("channelId", "videoId")
);

CREATE TABLE IF NOT EXISTS "subscriptions" (
  "subscriberChannelId" INTEGER NOT NULL REFERENCES "channels"("id") ON DELETE CASCADE, 
  "subscribedToChannelId" INTEGER NOT NULL REFERENCES "channels"("id") ON DELETE CASCADE,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("subscriberChannelId", "subscribedToChannelId")
);

CREATE TABLE IF NOT EXISTS "watchHistory" (
  "channelId" INTEGER NOT NULL REFERENCES "channels"("id") ON DELETE CASCADE,
  "videoId" INTEGER NOT NULL REFERENCES "videos"("id") ON DELETE CASCADE,
  "watchedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("channelId", "videoId", "watchedAt")
);

CREATE TABLE IF NOT EXISTS "watchLater" (
  "channelId" INTEGER NOT NULL REFERENCES "channels"("id") ON DELETE CASCADE,
  "videoId" INTEGER NOT NULL REFERENCES "videos"("id") ON DELETE CASCADE,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("channelId", "videoId")
);